name: Build on Push

on:
  push:

jobs:
  build_main:
    name: Build for ${{ matrix.os_short }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-20.04
          - ubuntu-latest
          - windows-latest
        include:
          - os: ubuntu-latest
            os_short: linux-latest
            binary_ext: so
            debug_ext: dbg
            cc: clang-14
            cxx: clang++-14

          - os: ubuntu-20.04
            os_short: linux-old
            binary_ext: so
            debug_ext: dbg
            cc: clang-9
            cxx: clang++-9

          - os: windows-latest
            os_short: windows-latest
            binary_ext: dll
            debug_ext: pdb
            cc: not-used
            cxx: not-used

    steps:
    - name: Install (Linux)
      if: runner.os == 'Linux'
      run: |
        sudo dpkg --add-architecture i386
        sudo apt-get update
        sudo apt-get install -y ${{ matrix.cc }} ${{ matrix.cxx }} g++-multilib
        echo "CC=${{ matrix.cc }}" >> $GITHUB_ENV
        echo "CXX=${{ matrix.cxx }}" >> $GITHUB_ENV

    - name: Setup MSBuild (Windows)
      if: runner.os == 'Windows'
      uses: microsoft/setup-msbuild@v1.3.1

    - name: Setup Python
      uses: actions/setup-python@v4.7.0
      with:
        python-version: '3.11'

    - name: Setup ambuild
      run: |
        python -m pip install wheel
        pip install git+https://github.com/alliedmodders/ambuild

    - name: Fetch Metamod-P
      uses: actions/checkout@v3.6.0
      with:
        path: metamod

    - name: Build Files
      working-directory: metamod
      run: |
        mkdir build
        cd build
        python3 ../configure.py --enable-optimize
        ambuild

    - uses: benjlevesque/short-sha@v2.2
      id: short-sha

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3.1.2
      with:
        name: metamod-p-${{ matrix.os_short }}-${{ steps.short-sha.outputs.sha }}
        path: |
            metamod/build/**/*.${{ matrix.binary_ext }}
            metamod/build/**/*.${{ matrix.debug_ext }}
